adversarial: TRADES
batch_size: 128
data_xform: none
dataset: cifar10
learning: full 
learning_rate: 0.1
loss_function: cross_entropy
model: resnet18
momentum: 0.9
num_epochs: 60
optimizer: SGD
weight_decay: 0.0005
scheduler: cosine